on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_DATABASE: "productDB"
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: pdo_mysql,bcmath

      - name: Install Composer
        run: |
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php composer-setup.php --install-dir=/usr/local/bin --filename=composer

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update Composer dependencies
        run: composer update

      - name: Copy .env.example file
        run: cp .env.example .env

      - name: Generate application key
        run: php artisan key:generate

      - name: Configure MySQL connection
        run: sed -i 's|DB_HOST=127.0.0.1|DB_HOST=mysql|' .env

      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install npm dependencies
        run: npm install

      - name: Build assets
        run: npm run build

      - name: Run unit tests
        run: vendor/bin/phpunit

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          
      - name: Install dpl
        run: gem install dpl

      - name: Deploy to Heroku
        run: dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
